// <auto-generated />
using System;
using Infrastructure.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(InfinityAppDbContext))]
    [Migration("20260105121103_PopularFichasEApontamentos")]
    partial class PopularFichasEApontamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoBotaDentro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaBotaDentroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdViagens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaBotaDentroId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ApontamentosBotaDentro", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoCBUQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EspessuraCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstacaFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacaInicial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Extensao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaCBUQId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaCBUQId");

                    b.ToTable("ApontamentosCBUQ", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoCBUQMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApontamentoCBUQId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ApontamentoCBUQId", "MaterialId");

                    b.ToTable("ApontamentosCBUQMateriais", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoFresagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EspessuraCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstacaFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacaInicial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Extensao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaFresagemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaFresagemId");

                    b.ToTable("ApontamentosFresagem", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoLimpezaPista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstacaFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacaInicial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Extensao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaLimpezaPistaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaLimpezaPistaId");

                    b.ToTable("ApontamentosLimpezaPista", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EspessuraCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstacaFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacaInicial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Extensao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaMicrorevestimentoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FracaoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FichaMicrorevestimentoId");

                    b.ToTable("ApontamentosMicrorevestimento", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimentoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApontamentoMicrorevestimentoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ApontamentoMicrorevestimentoId", "MaterialId");

                    b.ToTable("ApontamentosMicrorevestimentoMateriais", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoViagemCB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaViagemCBId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HoraCarregamento")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HoraDescarregamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdViagens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("FichaViagemCBId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ApontamentosViagemCB", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Deposito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Provisorio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("ObraId");

                    b.HasIndex("Provisorio");

                    b.ToTable("Depositos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Capacidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefixo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefixoObra")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Provisorio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.HasIndex("Placa");

                    b.HasIndex("Provisorio");

                    b.HasIndex("Tipo");

                    b.ToTable("Equipamentos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("Materiais", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Obras", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("ObraId", "Codigo");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Trecho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstacaFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstacaInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PistaDupla")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.HasIndex("PistaDupla");

                    b.HasIndex("ObraId", "Codigo");

                    b.ToTable("Trechos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaBotaDentro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositoDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositoOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("DepositoDestinoId");

                    b.HasIndex("DepositoOrigemId");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasBotaDentro", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaCBUQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasCBUQ", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaFresagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasFresagem", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaLimpezaPista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasLimpezaPista", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaMicrorevestimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasMicrorevestimento", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaViagemCB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Capacidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositoDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositoOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoExecucaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pista")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrechoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataProducao");

                    b.HasIndex("DepositoDestinoId");

                    b.HasIndex("DepositoOrigemId");

                    b.HasIndex("EquipamentoExecucaoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("Status");

                    b.HasIndex("TrechoId");

                    b.HasIndex("ObraId", "Numero");

                    b.ToTable("FichasViagemCB", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Logging.EntradaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextoJson")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Excecao")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tela")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("idx_logs_categoria");

                    b.HasIndex("Nivel")
                        .HasDatabaseName("idx_logs_nivel");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_logs_timestamp");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_logs_usuario");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Sincronizacao.FichaEquipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaViagemCBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("FichaViagemCBId", "EquipamentoId")
                        .IsUnique();

                    b.ToTable("FichasEquipamentos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Sincronizacao.FilaSincronizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FichaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasRealizadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoFicha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaTentativa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSincronizacao");

                    b.HasIndex("FichaId");

                    b.HasIndex("Status");

                    b.ToTable("FilaSincronizacao", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Sincronizacao.HistoricoSincronizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracaoSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ObraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeErro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeFichas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeSucesso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio");

                    b.HasIndex("ObraId");

                    b.HasIndex("Status");

                    b.HasIndex("Tipo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoSincronizacao", (string)null);
                });

            modelBuilder.Entity("MaterialServico", b =>
                {
                    b.Property<Guid>("MateriaisId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicosId")
                        .HasColumnType("TEXT");

                    b.HasKey("MateriaisId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("MaterialServico");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoBotaDentro", b =>
                {
                    b.HasOne("Domain.Entidades.Fichas.FichaBotaDentro", "FichaBotaDentro")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaBotaDentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaBotaDentro");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoCBUQ", b =>
                {
                    b.HasOne("Domain.Entidades.Fichas.FichaCBUQ", "FichaCBUQ")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaCBUQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaCBUQ");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoCBUQMaterial", b =>
                {
                    b.HasOne("Domain.Entidades.Apontamentos.ApontamentoCBUQ", "ApontamentoCBUQ")
                        .WithMany("Materiais")
                        .HasForeignKey("ApontamentoCBUQId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApontamentoCBUQ");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoFresagem", b =>
                {
                    b.HasOne("Domain.Entidades.Fichas.FichaFresagem", "FichaFresagem")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaFresagemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaFresagem");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoLimpezaPista", b =>
                {
                    b.HasOne("Domain.Entidades.Fichas.FichaLimpezaPista", "FichaLimpezaPista")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaLimpezaPistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaLimpezaPista");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimento", b =>
                {
                    b.HasOne("Domain.Entidades.Fichas.FichaMicrorevestimento", "FichaMicrorevestimento")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaMicrorevestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaMicrorevestimento");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimentoMaterial", b =>
                {
                    b.HasOne("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimento", "ApontamentoMicrorevestimento")
                        .WithMany("Materiais")
                        .HasForeignKey("ApontamentoMicrorevestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApontamentoMicrorevestimento");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoViagemCB", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Fichas.FichaViagemCB", "FichaViagemCB")
                        .WithMany("Apontamentos")
                        .HasForeignKey("FichaViagemCBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("FichaViagemCB");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Deposito", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany("Depositos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Domain.ObjetosDeValor.Coordenada", "Coordenada", b1 =>
                        {
                            b1.Property<Guid>("DepositoId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasPrecision(10, 6)
                                .HasColumnType("REAL")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(10, 6)
                                .HasColumnType("REAL")
                                .HasColumnName("Longitude");

                            b1.HasKey("DepositoId");

                            b1.ToTable("Depositos");

                            b1.WithOwner()
                                .HasForeignKey("DepositoId");
                        });

                    b.Navigation("Coordenada");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Equipamento", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany("Equipamentos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Servico", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany("Servicos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Trecho", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Deposito", null)
                        .WithMany("Trechos")
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany("Trechos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaBotaDentro", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Deposito", "DepositoDestino")
                        .WithMany()
                        .HasForeignKey("DepositoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Deposito", "DepositoOrigem")
                        .WithMany()
                        .HasForeignKey("DepositoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepositoDestino");

                    b.Navigation("DepositoOrigem");

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaCBUQ", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaFresagem", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaLimpezaPista", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaMicrorevestimento", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaViagemCB", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Deposito", "DepositoDestino")
                        .WithMany()
                        .HasForeignKey("DepositoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Deposito", "DepositoOrigem")
                        .WithMany()
                        .HasForeignKey("DepositoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Equipamento", "EquipamentoExecucao")
                        .WithMany()
                        .HasForeignKey("EquipamentoExecucaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Trecho", "Trecho")
                        .WithMany()
                        .HasForeignKey("TrechoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepositoDestino");

                    b.Navigation("DepositoOrigem");

                    b.Navigation("EquipamentoExecucao");

                    b.Navigation("Obra");

                    b.Navigation("Servico");

                    b.Navigation("Trecho");
                });

            modelBuilder.Entity("Domain.Entidades.Sincronizacao.FichaEquipamento", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Fichas.FichaViagemCB", "FichaViagemCB")
                        .WithMany("Equipamentos")
                        .HasForeignKey("FichaViagemCBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("FichaViagemCB");
                });

            modelBuilder.Entity("Domain.Entidades.Sincronizacao.HistoricoSincronizacao", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entidades.Comum.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MaterialServico", b =>
                {
                    b.HasOne("Domain.Entidades.Comum.Material", null)
                        .WithMany()
                        .HasForeignKey("MateriaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Comum.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoCBUQ", b =>
                {
                    b.Navigation("Materiais");
                });

            modelBuilder.Entity("Domain.Entidades.Apontamentos.ApontamentoMicrorevestimento", b =>
                {
                    b.Navigation("Materiais");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Deposito", b =>
                {
                    b.Navigation("Trechos");
                });

            modelBuilder.Entity("Domain.Entidades.Comum.Obra", b =>
                {
                    b.Navigation("Depositos");

                    b.Navigation("Equipamentos");

                    b.Navigation("Servicos");

                    b.Navigation("Trechos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaBotaDentro", b =>
                {
                    b.Navigation("Apontamentos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaCBUQ", b =>
                {
                    b.Navigation("Apontamentos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaFresagem", b =>
                {
                    b.Navigation("Apontamentos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaLimpezaPista", b =>
                {
                    b.Navigation("Apontamentos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaMicrorevestimento", b =>
                {
                    b.Navigation("Apontamentos");
                });

            modelBuilder.Entity("Domain.Entidades.Fichas.FichaViagemCB", b =>
                {
                    b.Navigation("Apontamentos");

                    b.Navigation("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
